name: 40 Congressional
favicon: null
layout_spectrum: 0.08289069146849215
typography_spectrum: 0.4394428364466876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfb4a1'
    - '#a27641'
    - '#494542'
    - '#fffffe'
    - '#261c15'
  brandStrength: 0.08752551348879933
  lightness: 0.5
  saturation: 0.06330234254710376
  rhythmicContrast: 0.23222846002317965
purpose: []
